apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-05908469afee92e8b # Replace with your actual EFS File System ID
  directoryPerms: "700"
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pvc
  labels:
    app: jenkins
spec:
  storageClassName: efs-sc
  capacity:
    storage: 1Gi  # Specify a small capacity; actual EFS usage can scale.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05908469afee92e8b # Replace with your EFS File System ID   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # Minimal storage request
  storageClassName: efs-sc
